name: Auto Merge Dependabot Security Updates
on:
  pull_request:
    types: [labeled, opened, synchronize]
  workflow_call:
    inputs: {}
  
jobs:
  call-automerge:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - name: Automerge Dependabot PRs
        uses: ./github/actions/auto-approve-dependabot
